# Generated by Django 2.1.5 on 2020-12-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=500, null=True)),
                ('content', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
