# Generated by Django 2.1.5 on 2020-12-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('ID', models.CharField(max_length=20)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
