# Generated by Django 2.1.5 on 2020-12-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
